platform :ios, '8.0'

target 'SmartScreenshot' do
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => '../node_modules/react-native'
    pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker/ios'
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
end